import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Bestselling from "@/components/bribooksstore/bestselling/Bestselling";
import Footer from "@/components/bribooksstore/footer/Footer";
import Toprated from "@/components/bribooksstore/toprated/Toprated";
import Header from "@/components/bribooksstore/head/Navbar";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isbooks, setIsBooks] = useState([]);

  const fetchBooks = async () => {
    try {
      const response = await fetch(
        // "https://crm.dev.bribooks.com/api/getBooks",
        "https://api.bribooks.com/api/getBooks",
        {
          method: "POST",
        }
      );
      const fetdata = await response.json();
      setIsBooks(fetdata.books || []);
    } catch (error) {
      console.error("Failed to fetch books", error);
    }
  };

  useEffect(() => {
    fetchBooks();
  }, []);
  return (
    <>
      <Head>
        <title>BriBook Store</title>
        <meta name="description" content="Generated by BriBooks" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}></div>
        
      </main> */}
      <Header books={isbooks} />
      <Bestselling />
      <Toprated />
      <Footer />
    </>
  );
}
