import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Bestselling from "@/components/bribooksstore/bestselling/Bestselling";
import Footer from "@/components/bribooksstore/footer/Footer";
import Toprated from "@/components/bribooksstore/toprated/Toprated";
import Header from "@/components/bribooksstore/head/Navbar";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>BriBook Store</title>
        <meta name="description" content="Generated by BriBooks" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      {/* <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}></div>
        
      </main> */}
      <Header />
        <Bestselling />
        <Toprated />
        <Footer />
    </>
  );
}
